architecture: v0.1.5
callback_patience: 20
codes:
- certainty
- confusion
- neutral_statement
dataset_name: confusion_examples.yml
embedding_model: https://tfhub.dev/google/universal-sentence-encoder-multilingual/3
epochs: 500
l1_reg: 0.01
l2_reg: 0.01
learning_rate: 0.0005
min_words: 1
sent_dropout: 0.3
sent_hl_units: 64
stop_words_file: null
task: train
validation_split: 0.2
wandb_project: test_wandb
